### ISSUE TITLE
This package breaks if you're using plone.protect

### ISSUE THREAD

**Issue by idgserpro** [ida/adi.trash#3]
When using a Plone 4.3.x installation with https://github.com/plone/plone.protect and trying to delete an object and the root of the site with a url like `folder_contents?_authenticator=2c4b1c9a84b7d48b7ef39080239c62db34406382`, you get

```
2017-07-26 16:07:54 ERROR Zope.SiteErrorLog 1501096074.850.287455953144 http://localhost:18928/Plone/@@adi_trash_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module adi.trash.browser.browser, line 63, in __call__
  Module plone.api.content, line 2, in move
  Module plone.api.validation, line 70, in wrapped
  Module plone.api.content, line 2, in move
  Module plone.api.validation, line 131, in wrapped
  Module plone.api.content, line 190, in move
  Module OFS.CopySupport, line 206, in manage_pasteObjects
  Module plone.dexterity.content, line 214, in _verifyObjectPaste
  Module Products.CMFCore.PortalFolder, line 421, in _verifyObjectPaste
ValueError: Disallowed subobject type: Plone Site
```

This happens because of this line: https://github.com/ida/adi.trash/blob/740c00fa95fce73677faef316f4a982b6da4d5e9/adi/trash/browser/browser.py#L33

```
if landing_url.endswith('/folder_contents'):
```

The if is always ` False` and you wrongly enter in `# We're coming from a folder_contents' delete-button:` condition, when actually you're not there.

Something more robust should be used instead, like

```
from urlparse import urlparse
# We're coming from a folder_contents' delete-button:
if urlparse(landing_url).path.endswith('/folder_contents'):
```

This is a nice time to start adding tests infrastructure to this package.

**Comment by ida** [comment]
Thank you for the report and solution! May I ask who you are? I'd be happy to grant you co-ownership, if you like.

**Comment by idgserpro** [comment]
This is a corporate account for Serpro, Brazilian government, used specially in https://github.com/plonegovbr/. Adding `idgserpro` on CHANGES like you did before is fine, that's what is being added in all packages we're dealing with.
