### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [ida/adi.trash#6]
Hello !

is it possible to make a new release of this package ?

Thank you and regards,

Laurent.

**Comment by ida** [comment]
Hi, thanks for your request. Newest changes are out since 3rd of March, with vs. 0.4 Cheers, Ida

**Comment by laulaz** [comment]
Cool, thanks a lot @ida!
I din't see any release commit so I tought it hasn't been done.

**Comment by ida** [comment]
Oh yes, I noticed that now, too (see #5), CHANGES gonna be included with next release. Cheers!
